### ISSUE TITLE
Broken in Legion

### ISSUE THREAD

**Issue by 2ndHouse** [TekNoLogic/StealYourCarbon#14]
No longer works with the current patch. Seeing two errors when opening a vendor window...

`StealYourCarbon\VendorBuyer.lua:12: attempt to call global 'GetAuctionItemClasses' (a nil value)
StealYourCarbon\VendorBuyer.lua:12: in main chunk
[C]: in function `LoadAddOn'
AddonLoader\AddonLoader-r135.lua:136: in function `LoadAddOn'
AddonLoader\AddonLoader-r135.lua:170: in function <AddonLoader\AddonLoader.lua:147>`

`StealYourCarbon\StealYourCarbon-6.0.0.25-Beta.lua:9: attempt to call field 'MERCHANT_SHOW' (a nil value)
StealYourCarbon\StealYourCarbon-6.0.0.25-Beta.lua:9: in function `OnLoad'
StealYourCarbon\externals\events.lua:57: in function <StealYourCarbon\externals\events.lua:41>
StealYourCarbon\externals\events.lua:89: in function <StealYourCarbon\externals\events.lua:88>
[C]: in function `LoadAddOn'
AddonLoader\AddonLoader-r135.lua:136: in function `LoadAddOn'
AddonLoader\AddonLoader-r135.lua:170: in function <AddonLoader\AddonLoader.lua:147>`

**Comment by 2ndHouse** [comment]
Not sure what's going on with the code markup above, can't seem to fix it. Anyway, two separate errors there, just screwy formatting.

**Comment by 2ndHouse** [comment]
I thought maybe these errors were just AddonLoader related, but I tried changing the parameters in the AddonLoader options and even deleting AddonLoader out of the SYC toc, but was still getting errors.

**Comment by tekkub** [comment]
Dun fixed ^^
