### ISSUE TITLE
Please Tek, fix this Addon 

### ISSUE THREAD

**Issue by Imiona** [TekNoLogic/StealYourCarbon#15]
I use this since BC and it would be a damn shame if i had to use something else now :)

Buggraber:

1x StealYourCarbon\VendorBuyer.lua:12: attempt to call global 'GetAuctionItemClasses' (a nil value)
StealYourCarbon\VendorBuyer.lua:12: in main chunk

Locals:
myname = "StealYourCarbon"
ns = <table> {
 BANKFRAME_OPENED = <function> defined @StealYourCarbon\Bank.lua:103
 ids = <table> {
 }
 RegisterEvent = <function> defined @StealYourCarbon\externals\events.lua:8
 UnregisterAllEvents = <function> defined @StealYourCarbon\externals\events.lua:19
 GSC = <function> defined @StealYourCarbon\externals\gsc.lua:18
 OnLoad = <function> defined @StealYourCarbon\StealYourCarbon.lua:6
 GS = <function> defined @StealYourCarbon\externals\gsc.lua:44
 dbpcname = "StealYourCarbonDB"
 Printf = <function> defined @StealYourCarbon\externals\print.lua:6
 Print = <function> defined @StealYourCarbon\externals\print.lua:5
 UnregisterEvent = <function> defined @StealYourCarbon\externals\events.lua:14
 G = <function> defined @StealYourCarbon\externals\gsc.lua:57
}
stacks = <table> {
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetAuctionItemClasses' (a nil value)"

**Comment by tekkub** [comment]
Just did ^^
